version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.30.4
    container_name: n8n_local
    restart: always
    ports:
      - "5678:5678"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      # Network and domain
      - N8N_HOST=${NGROK_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_WEBHOOK_URL=https://${NGROK_HOST}/
      
      # Security and reverse proxy (ngrok)
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PROXY_HOPS=1
      - N8N_SECURE_COOKIE=false
      
      # Features and AI (MCP)
      - N8N_TELEMETRY_ENABLED=false
      - N8N_MCP_BASE_URL=https://${NGROK_HOST}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: